import { useState, useEffect } from 'react'
import { X, DollarSign, CheckCircle, Loader2 } from 'lucide-react'
import { useUpdateDealNotes } from '@/hooks/useApi'

interface AnalysisResults {
  maxAllowableOffer: number
  rule70Pass: boolean
  capRate: number
  cashOnCash: number
  monthlyCashFlow: number
  brrrrEquity: number
}

interface DealAnalyzerModalProps {
  isOpen: boolean
  onClose: () => void
  dealId: string
  dealTitle: string
  defaultAskingPrice?: number
}

function formatCurrency(value: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value)
}

function calculateMonthlyMortgage(
  loanAmount: number,
  annualRate: number,
  termYears: number
): number {
  if (loanAmount <= 0 || annualRate <= 0 || termYears <= 0) return 0
  const monthlyRate = annualRate / 100 / 12
  const termMonths = termYears * 12
  return (loanAmount * monthlyRate) / (1 - Math.pow(1 + monthlyRate, -termMonths))
}

export default function DealAnalyzerModal({
  isOpen,
  onClose,
  dealId,
  dealTitle,
  defaultAskingPrice,
}: DealAnalyzerModalProps) {
  const updateNotes = useUpdateDealNotes()

  const [arv, setArv] = useState('')
  const [purchasePrice, setPurchasePrice] = useState('')
  const [repairEstimate, setRepairEstimate] = useState('')
  const [rentEstimate, setRentEstimate] = useState('')
  const [downPayment, setDownPayment] = useState('20')
  const [interestRate, setInterestRate] = useState('7')
  const [loanTermYears, setLoanTermYears] = useState('30')
  const [results, setResults] = useState<AnalysisResults | null>(null)
  const [saveState, setSaveState] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle')

  useEffect(() => {
    if (defaultAskingPrice) {
      setPurchasePrice(String(defaultAskingPrice))
    }
  }, [defaultAskingPrice])

  if (!isOpen) return null

  const calculateResults = () => {
    const arvNum = parseFloat(arv) || 0
    const ppNum = parseFloat(purchasePrice) || 0
    const repairNum = parseFloat(repairEstimate) || 0
    const rentNum = parseFloat(rentEstimate) || 0
    const dpPct = parseFloat(downPayment) || 0
    const rateNum = parseFloat(interestRate) || 0
    const termNum = parseFloat(loanTermYears) || 30

    const maxAllowableOffer = arvNum * 0.70 - repairNum
    const rule70Pass = ppNum <= maxAllowableOffer

    const loanAmount = ppNum * (1 - dpPct / 100)
    const monthlyMortgage = calculateMonthlyMortgage(loanAmount, rateNum, termNum)
    const monthlyExpenses = rentNum * 0.40
    const monthlyCashFlow = rentNum - monthlyMortgage - monthlyExpenses

    const annualNetIncome = (rentNum - monthlyExpenses) * 12
    const capRate = ppNum > 0 ? (annualNetIncome / ppNum) * 100 : 0

    const downPaymentAmount = ppNum * (dpPct / 100)
    const annualCashFlow = monthlyCashFlow * 12
    const cashOnCash = downPaymentAmount > 0 ? (annualCashFlow / downPaymentAmount) * 100 : 0

    const brrrrEquity = arvNum - ppNum - repairNum

    setResults({
      maxAllowableOffer,
      rule70Pass,
      capRate,
      cashOnCash,
      monthlyCashFlow,
      brrrrEquity,
    })
    setSaveState('idle')
  }

  const handleSaveNotes = async () => {
    if (!results) return
    setSaveState('saving')

    const notesText = [
      `Deal Analysis — ${dealTitle}`,
      '',
      `ARV: ${formatCurrency(parseFloat(arv) || 0)}`,
      `Purchase Price: ${formatCurrency(parseFloat(purchasePrice) || 0)}`,
      `Repair Estimate: ${formatCurrency(parseFloat(repairEstimate) || 0)}`,
      '',
      `70% Rule: ${results.rule70Pass ? 'PASS' : 'FAIL'} (Max Offer: ${formatCurrency(results.maxAllowableOffer)})`,
      `Cap Rate: ${results.capRate.toFixed(2)}%`,
      `Cash-on-Cash: ${results.cashOnCash.toFixed(2)}%`,
      `Monthly Cash Flow: ${formatCurrency(results.monthlyCashFlow)}`,
      `BRRRR Equity: ${formatCurrency(results.brrrrEquity)}`,
      '',
      'Generated by REI Fundamentals Hub',
    ].join('\n')

    try {
      await updateNotes.mutateAsync({ dealId, notes: notesText })
      setSaveState('saved')
    } catch {
      setSaveState('error')
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/30" onClick={onClose} />

      {/* Panel */}
      <div className="relative bg-white rounded-xl shadow-xl w-full max-w-lg mx-auto mt-20 border border-slate-200 max-h-[calc(100vh-120px)] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-slate-200 sticky top-0 bg-white rounded-t-xl">
          <h2 className="text-lg font-semibold text-slate-800">Deal Analyzer</h2>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>

        <div className="p-5 space-y-5">
          {/* Inputs */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-medium text-slate-500 mb-1">ARV ($)</label>
              <div className="relative">
                <DollarSign className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
                <input
                  type="number"
                  value={arv}
                  onChange={(e) => setArv(e.target.value)}
                  placeholder="0"
                  min="0"
                  className="w-full pl-8 pr-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-500 mb-1">Purchase Price ($)</label>
              <div className="relative">
                <DollarSign className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
                <input
                  type="number"
                  value={purchasePrice}
                  onChange={(e) => setPurchasePrice(e.target.value)}
                  placeholder="0"
                  min="0"
                  className="w-full pl-8 pr-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-500 mb-1">Repair Estimate ($)</label>
              <div className="relative">
                <DollarSign className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
                <input
                  type="number"
                  value={repairEstimate}
                  onChange={(e) => setRepairEstimate(e.target.value)}
                  placeholder="0"
                  min="0"
                  className="w-full pl-8 pr-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-500 mb-1">Monthly Rent ($)</label>
              <div className="relative">
                <DollarSign className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
                <input
                  type="number"
                  value={rentEstimate}
                  onChange={(e) => setRentEstimate(e.target.value)}
                  placeholder="0"
                  min="0"
                  className="w-full pl-8 pr-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-500 mb-1">Down Payment (%)</label>
              <input
                type="number"
                value={downPayment}
                onChange={(e) => setDownPayment(e.target.value)}
                placeholder="20"
                min="0"
                max="100"
                className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-500 mb-1">Interest Rate (%)</label>
              <input
                type="number"
                value={interestRate}
                onChange={(e) => setInterestRate(e.target.value)}
                placeholder="7"
                min="0"
                step="0.1"
                className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
              />
            </div>

            <div className="col-span-2">
              <label className="block text-xs font-medium text-slate-500 mb-1">Loan Term (years)</label>
              <input
                type="number"
                value={loanTermYears}
                onChange={(e) => setLoanTermYears(e.target.value)}
                placeholder="30"
                min="1"
                className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
              />
            </div>
          </div>

          <button
            onClick={calculateResults}
            className="w-full px-4 py-2.5 bg-primary-500 text-white rounded-lg hover:bg-primary-600 transition-colors text-sm font-medium"
          >
            Run Analysis
          </button>

          {/* Results */}
          {results && (
            <div className="space-y-4 pt-2">
              <h3 className="text-sm font-semibold text-slate-700 uppercase tracking-wide">Results</h3>

              <div className="space-y-2.5">
                {/* 70% Rule */}
                <div className="flex items-center justify-between py-2 px-3 bg-slate-50 rounded-lg">
                  <div>
                    <p className="text-sm font-medium text-slate-700">70% Rule</p>
                    <p className="text-xs text-slate-500">Max Offer: {formatCurrency(results.maxAllowableOffer)}</p>
                  </div>
                  <span
                    className={`px-2.5 py-0.5 text-xs font-bold rounded-full ${
                      results.rule70Pass
                        ? 'bg-green-100 text-green-700'
                        : 'bg-red-100 text-red-700'
                    }`}
                  >
                    {results.rule70Pass ? 'PASS' : 'FAIL'}
                  </span>
                </div>

                {/* Cap Rate */}
                <div className="flex items-center justify-between py-2 px-3 bg-slate-50 rounded-lg">
                  <p className="text-sm font-medium text-slate-700">Cap Rate</p>
                  <p className="text-sm font-semibold text-slate-800">{results.capRate.toFixed(2)}%</p>
                </div>

                {/* Cash-on-Cash */}
                <div className="flex items-center justify-between py-2 px-3 bg-slate-50 rounded-lg">
                  <p className="text-sm font-medium text-slate-700">Cash-on-Cash</p>
                  <p className="text-sm font-semibold text-slate-800">{results.cashOnCash.toFixed(2)}%</p>
                </div>

                {/* Monthly Cash Flow */}
                <div className="flex items-center justify-between py-2 px-3 bg-slate-50 rounded-lg">
                  <p className="text-sm font-medium text-slate-700">Monthly Cash Flow</p>
                  <p
                    className={`text-sm font-semibold ${
                      results.monthlyCashFlow >= 0 ? 'text-green-600' : 'text-red-600'
                    }`}
                  >
                    {formatCurrency(results.monthlyCashFlow)}
                  </p>
                </div>

                {/* BRRRR Equity */}
                <div className="flex items-center justify-between py-2 px-3 bg-slate-50 rounded-lg">
                  <p className="text-sm font-medium text-slate-700">BRRRR Equity</p>
                  <p className="text-sm font-semibold text-slate-800">{formatCurrency(results.brrrrEquity)}</p>
                </div>
              </div>

              {/* Save to GHL */}
              <div className="pt-2 border-t border-slate-200">
                {saveState === 'saved' ? (
                  <div className="flex items-center justify-center gap-2 py-2.5 text-sm font-medium text-green-600">
                    <CheckCircle className="w-4 h-4" />
                    Saved to GHL
                  </div>
                ) : (
                  <button
                    onClick={handleSaveNotes}
                    disabled={saveState === 'saving'}
                    className="w-full flex items-center justify-center gap-2 px-4 py-2.5 border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {saveState === 'saving' ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Saving...
                      </>
                    ) : (
                      'Save Analysis to Deal Notes'
                    )}
                  </button>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
